In [12]:
import sys  
print (sys.version)

3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4]


In [4]:
test = "Hello World"

In [27]:
print(test)

Hello World


## sigmoid 函数
$ sigmoid(x) = {1 \over 1 + e^{-x} } $
<img src="Sigmoid.png" style = "width:500px;height:228px;">

In [8]:
import numpy
import math
def Basic_sigmoid(x):
    y = 1 /(1+ math.exp(-x))
    return y

In [9]:
Basic_sigmoid(3)

0.9525741268224334

## Math库不支持向量化运算，无法提高运算速度

In [10]:
X=[1,2,3,4]
Basic_sigmoid(X)

TypeError: bad operand type for unary -: 'list'

In [5]:
import numpy as np
def sigmoid(x):
    y = 1 / (1+ np.exp(-x))
    return y

In [6]:
X = [1,2,3,4]
sigmoid(X)

TypeError: bad operand type for unary -: 'list'

## 向量化操作，必须使用np.array输入向量

In [7]:
X = np.array([1,2,3,4])
sigmoid(X)

array([ 0.73105858,  0.88079708,  0.95257413,  0.98201379])

## sigmoid 导数
\begin{equation}
sigmoid ' (x) = e^{-x}{1 \over \left( 1+e^{-x} \right)^2} = (1-sigmoid(x))sigmoid(x)
\end{equation}

In [ ]:
def sigmoid_derivate(x):
    sigmoid = 1/(1+ np.exp(-x))
    y = (1-sigmoid)*sigmoid
    return y

In [ ]:
X = np.array([1,2,3,4])
print("sigmoid derivation is %s" % str(sigmoid_derivate(X)))

## python 矩阵操作
### np.array.shape 返回(depth,length,heigth)
### np.array.reshape() 调整矩阵形状

In [31]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]],
                 
       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

image1 = np.array([[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]])


print(image)
print(image.shape)
print(image.reshape(3,4,2))
print(image.reshape(3,4,2).shape)


print(image1)
print(image1.shape)
print(image1.reshape(1,3,2))
print(image1.reshape(1,3,2).shape)

[[[ 0.67826139  0.29380381]
  [ 0.90714982  0.52835647]
  [ 0.4215251   0.45017551]]

 [[ 0.92814219  0.96677647]
  [ 0.85304703  0.52351845]
  [ 0.19981397  0.27417313]]

 [[ 0.60659855  0.00533165]
  [ 0.10820313  0.49978937]
  [ 0.34144279  0.94630077]]

 [[ 0.60659855  0.00533165]
  [ 0.10820313  0.49978937]
  [ 0.34144279  0.94630077]]]
(4, 3, 2)
[[[ 0.67826139  0.29380381]
  [ 0.90714982  0.52835647]
  [ 0.4215251   0.45017551]
  [ 0.92814219  0.96677647]]

 [[ 0.85304703  0.52351845]
  [ 0.19981397  0.27417313]
  [ 0.60659855  0.00533165]
  [ 0.10820313  0.49978937]]

 [[ 0.34144279  0.94630077]
  [ 0.60659855  0.00533165]
  [ 0.10820313  0.49978937]
  [ 0.34144279  0.94630077]]]
(3, 4, 2)
[[ 0.67826139  0.29380381]
 [ 0.90714982  0.52835647]
 [ 0.4215251   0.45017551]]
(3, 2)
[[[ 0.67826139  0.29380381]
  [ 0.90714982  0.52835647]
  [ 0.4215251   0.45017551]]]
(1, 3, 2)


In [ ]:
def image2vec(img):
    """
    img is (depth, length,heigth)
    """
    
    v = img.reshape(img.shape[0]*img.shape[1], img.shape[2])
    return v

In [33]:
print("image shape is "+str(image.shape))
print(image2vec(image))
print("image reshape is "+str(image2vec(image).shape))

image shape is (4, 3, 2)
[[ 0.67826139  0.29380381]
 [ 0.90714982  0.52835647]
 [ 0.4215251   0.45017551]
 [ 0.92814219  0.96677647]
 [ 0.85304703  0.52351845]
 [ 0.19981397  0.27417313]
 [ 0.60659855  0.00533165]
 [ 0.10820313  0.49978937]
 [ 0.34144279  0.94630077]
 [ 0.60659855  0.00533165]
 [ 0.10820313  0.49978937]
 [ 0.34144279  0.94630077]]
image reshape is (12, 2)


## 归一化
归一化后地图下降速度加快
np.linalg.norm(x, order, axis, keepdims)
ord 表示归一化范数方式
axis 0表示列向量归一化，1表示行向量归一化
keepdims 保持归一化后的向量shape，便于后续的Broadcasting

In [42]:
vec = np.array([
    [0, 3, 4],
    [1, 6, 4]])
y = np.linalg.norm(vec, ord=2, axis=1, keepdims=False)
print(y)
print(y.shape)

[ 5.          7.28010989]
(2,)


In [41]:
def normalize_row(x):
    x_norm = np.linalg.norm(x, ord=2, axis=1, keepdims=True)
    y = x/x_norm
    return y

In [50]:
print( "行向量归一化：" +str(normalize_row(vec)))
print(np.linalg.norm(normalize_row(vec), ord=2, axis=1, keepdims=True))

行向量归一化：[[ 0.          0.6         0.8       ]
 [ 0.13736056  0.82416338  0.54944226]]
[[ 1.]
 [ 1.]]


## Broadcasting 

**Instructions**:
- $ \text{for } x \in \mathbb{R}^{1\times n} \text{,     } softmax(x) = softmax(\begin{bmatrix}
    x_1  &&
    x_2 &&
    ...  &&
    x_n  
\end{bmatrix}) = \begin{bmatrix}
     \frac{e^{x_1}}{\sum_{j}e^{x_j}}  &&
    \frac{e^{x_2}}{\sum_{j}e^{x_j}}  &&
    ...  &&
    \frac{e^{x_n}}{\sum_{j}e^{x_j}} 
\end{bmatrix} $ 

- $\text{for a matrix } x \in \mathbb{R}^{m \times n} \text{,  $x_{ij}$ maps to the element in the $i^{th}$ row and $j^{th}$ column of $x$, thus we have: }$  $$softmax(x) = softmax\begin{bmatrix}
    x_{11} & x_{12} & x_{13} & \dots  & x_{1n} \\
    x_{21} & x_{22} & x_{23} & \dots  & x_{2n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    x_{m1} & x_{m2} & x_{m3} & \dots  & x_{mn}
\end{bmatrix} = \begin{bmatrix}
    \frac{e^{x_{11}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{12}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{13}}}{\sum_{j}e^{x_{1j}}} & \dots  & \frac{e^{x_{1n}}}{\sum_{j}e^{x_{1j}}} \\
    \frac{e^{x_{21}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{22}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{23}}}{\sum_{j}e^{x_{2j}}} & \dots  & \frac{e^{x_{2n}}}{\sum_{j}e^{x_{2j}}} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    \frac{e^{x_{m1}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m2}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m3}}}{\sum_{j}e^{x_{mj}}} & \dots  & \frac{e^{x_{mn}}}{\sum_{j}e^{x_{mj}}}
\end{bmatrix} = \begin{pmatrix}
    softmax\text{(first row of x)}  \\
    softmax\text{(second row of x)} \\
    ...  \\
    softmax\text{(last row of x)} \\
\end{pmatrix} $$

In [52]:
def softmax(x):
    exp_x = np.exp(x)
    sum_x = np.sum(exp_x, axis=1, keepdims=True)
    y = exp_x/sum_x
    return y

In [54]:
x = np.array([[9, 2, 5, 0, 0],
              [7, 5, 0, 0 ,0]])
print("softmax(x) is " + str(softmax(x)))

softmax(x) is [[  9.80897665e-01   8.94462891e-04   1.79657674e-02   1.21052389e-04
    1.21052389e-04]
 [  8.78679856e-01   1.18916387e-01   8.01252314e-04   8.01252314e-04
    8.01252314e-04]]


## 总结
- np.exp(x)对np.array类型的每个元素进行指数运算
- sigmoid函数的曲线和导数表达式
- 矩阵形状调整，注意shape输出的含义
- np.linalg可以进行矩阵的归一化
- Broadcasting是numpy很重要的性质

## 比较使用np的矩阵运算函数和fo循环的时间效率
### np 常用乘法运算函数
- np.dot() 向量间的内积，矩阵与向量的乘法
- np.outer() 向量间的外积
- np.multiply() 向量对应元素的乘积

In [45]:
import time
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

# 向量内积
tic = time.process_time()
dot=0
for i in range(len(x1)):
    dot += x1[i]*x2[i]
toc = time.process_time()
print("dot for loop processing time is " + str(1000*(toc - tic)) + "ms")

#矩阵乘法
tic = time.process_time()
outer = np.zeros((len(x1),len(x2)))
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print("outer for loop processing time is " + str(1000*(toc - tic)) + "ms")

#对应元素相乘
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
        mul[i] = x1[i]*x2[i]
toc = time.process_time()
print("element multiple for loop processing time is " + str(1000*(toc - tic)) + "ms")

#矩阵与向量乘积
W = np.random.rand(3, len(x1))
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] = W[i,j]*x2[j]
toc = time.process_time()
print("Matrix x vec for loop processing time is " + str(1000*(toc - tic)) + "ms")


dot for loop processing time is 0.09364200000039347ms
outer for loop processing time is 0.32475700000000884ms
element multiple for loop processing time is 0.11617700000021713ms
Matrix x vec for loop processing time is 0.17941999999981917ms


In [47]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

# 向量内积
tic = time.process_time()
dot=np.dot(x1,x2)
toc = time.process_time()
print("dot for loop processing time is " + str(1000*(toc - tic)) + "ms")

#矩阵乘法
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print("outer for loop processing time is " + str(1000*(toc - tic)) + "ms")

#对应元素相乘
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print("element multiple for loop processing time is " + str(1000*(toc - tic)) + "ms")

#矩阵与向量乘积
tic = time.process_time()
gdot = np.dot(W,x1)
toc = time.process_time()
print("Matrix x vec for loop processing time is " + str(1000*(toc - tic)) + "ms")


dot for loop processing time is 0.13329100000003535ms
outer for loop processing time is 0.10771200000014858ms
element multiple for loop processing time is 0.0671310000002201ms
Matrix x vec for loop processing time is 0.1143310000002451ms


## 通过向量化表示计算代价函数L1, L2

In [52]:
def L1(yhat, y):
    loss = sum(abs(yhat-y))
    return loss

In [55]:
y = np.array([1, 0, 0, 1, 1])
yhat = np.array([.9, 0.2, 0.1, .4, .9])
print("L1 loss function is %.2f" %L1(yhat,y) )

L1 loss function is 1.10


In [57]:
def L2(yhat,y):
    loss = sum((yhat-y)**2)
    return loss

In [59]:
print("L1 loss function is %.2f" %L2(yhat,y) )

L1 loss function is 0.43
